exec: ../hello
args:
    - Hello World 1
host: tealc-mint
extra-hosts:
    - pong
    - www.mysite.com
static-hosts:
    - host: foobar
      root: ..
    - host: unsafe1
      root: ../../
    - host: unsafe2
      root: /home
redirects:
    - from: mysite.com
      to: www.mysite.com
