exec: ../hello
args:
    - Hello World 1
host: tealc-mint
extra-hosts:
    - pong
static-hosts:
    - host: foobar
      root: ..
    - host: unsafe1
      root: ../../
    - host: unsafe2
      root: /home
